---
title: "The Ridge Regression"
author: "Wenfeng Zhang"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: yes
    toc: true
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{The ridge regression vignette}
-->

## The ridge regression function

Use iris as example
```{r}
library(bis557)
fit <- ridge_reg(Sepal.Length ~ .,1.2, iris)
fit
```

## Look at effect on the out-of-sample mean square error as $\lambda$ varies

```{r}
data("ridge_train")
data("ridge_test")
# write function for calculating mse
ridge_mse <- function(formula, lambda, train_set, test_set){
  coef <- ridge_reg(formula, lambda, train_set)$coef
  x.test <- as.matrix(model.matrix(formula, test_set))
  y.test <- test_set[,as.character(formula)[2]]
  pred.test <- x.test%*%coef
  mse <- sum((pred.test-y.test)^2)/length(y.test)
  mse
}

# set lambda values
# singular values

x <- as.matrix(model.matrix(y ~.,ridge_train))
svd_obj <- svd(x)
lambda.range <- range(svd_obj[["d"]])^2
lambda <- seq(0,lambda.range[2], 0.5)
mse <- sapply(lambda, function(lambda) 
          ridge_mse(y ~., lambda, ridge_train, ridge_test))

# plot
plot(mse~log(lambda), type = "l")
lambda[which(mse == min(mse))]
```

Achieve lowest mse when lambda is set to 29.5